# Generated by Django 5.1.1 on 2024-09-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
    ]
