# Generated by Django 5.1.1 on 2024-09-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20240920_1135'),
    ]

    operations = [
    ]
